import os
import pwd
import grp
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple


SUPPORTED_COMMANDS = [
    "apt",
    "apt-get",
    "dnf",
    "yum",
    "pacman",
    "zypper",
    "snap",
    "systemctl",
]


@dataclass
class PrivilegedSetupResult:
    ok: bool
    message: str
    details: Dict[str, object]


@dataclass
class PrivilegedCheckResult:
    ok: bool
    message: str
    details: Dict[str, object]


def _detect_installed_commands() -> List[str]:
    installed: List[str] = []
    for cmd in SUPPORTED_COMMANDS:
        path = shutil.which(cmd)
        if path and path not in installed:
            installed.append(path)
    return installed


def _build_command_specs(paths: List[str]) -> List[str]:
    specs: List[str] = []
    for path in paths:
        specs.append(path)
        specs.append(f"{path} *")
    return specs


def _build_sudoers_content(target_user: str, cmd_specs: List[str]) -> str:
    cmd_alias = ", ".join(cmd_specs)
    return (
        "# Managed by Assistant-OS.\n"
        "# Generated by: agent.py doctor --setup-privileged\n"
        f"User_Alias AOSD_USER = {target_user}\n"
        f"Cmnd_Alias AOSD_SAFE_CMDS = {cmd_alias}\n"
        "AOSD_USER ALL=(root) NOPASSWD: AOSD_SAFE_CMDS\n"
    )


def _resolve_target_user(user: Optional[str]) -> Tuple[bool, str]:
    if user:
        try:
            pwd.getpwnam(user)
            return True, user
        except KeyError:
            return False, f"User '{user}' does not exist on this system."

    env_user = os.getenv("SUDO_USER") or os.getenv("USER")
    if env_user:
        try:
            pwd.getpwnam(env_user)
            return True, env_user
        except KeyError:
            pass

    try:
        return True, pwd.getpwuid(os.getuid()).pw_name
    except Exception:
        return False, "Unable to determine target user automatically. Use --user."


def _run_visudo_check(file_path: str, *, use_sudo: bool = False, non_interactive: bool = False) -> Tuple[bool, str]:
    visudo = shutil.which("visudo")
    if not visudo:
        return False, "'visudo' not found. Install sudo package first."
    cmd = [visudo, "-cf", file_path]
    if use_sudo:
        sudo_bin = shutil.which("sudo")
        if not sudo_bin:
            return False, "'sudo' not found but elevated validation was requested."
        cmd = [sudo_bin]
        if non_interactive:
            cmd.append("-n")
        cmd.extend([visudo, "-cf", file_path])
    proc = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if proc.returncode == 0:
        return True, "sudoers syntax is valid."
    details = (proc.stdout or "") + ("\n" + proc.stderr if proc.stderr else "")
    return False, details.strip() or "visudo validation failed."


def check_privileged_access(
    *,
    user: Optional[str] = None,
    destination: str = "/etc/sudoers.d/assistant-os",
) -> PrivilegedCheckResult:
    ok_user, user_or_error = _resolve_target_user(user)
    if not ok_user:
        return PrivilegedCheckResult(ok=False, message=user_or_error, details={})
    target_user = user_or_error

    if not os.path.exists(destination):
        return PrivilegedCheckResult(
            ok=False,
            message="Privileged sudoers file not found.",
            details={"destination": destination, "user": target_user},
        )

    content: str = ""
    try:
        with open(destination, "r", encoding="utf-8", errors="ignore") as fh:
            content = fh.read()
    except Exception as e:
        if isinstance(e, PermissionError) and os.geteuid() != 0:
            ok_valid, validation_msg = _run_visudo_check(destination, use_sudo=True, non_interactive=True)
            if ok_valid:
                return PrivilegedCheckResult(
                    ok=True,
                    message="Privileged sudo setup is active (validated without reading content).",
                    details={"destination": destination, "validation": validation_msg, "user": target_user},
                )
            return PrivilegedCheckResult(
                ok=True,
                message="Privileged sudo setup file detected (non-root read restricted).",
                details={
                    "destination": destination,
                    "note": "File exists with restricted permissions; skipping content-level validation for non-root user.",
                    "user": target_user,
                },
            )
        return PrivilegedCheckResult(
            ok=False,
            message="Failed to read privileged sudoers file.",
            details={"destination": destination, "error": str(e), "user": target_user},
        )

    if "AOSD_USER" not in content or "AOSD_SAFE_CMDS" not in content:
        return PrivilegedCheckResult(
            ok=False,
            message="Sudoers file exists but does not look like assistant-managed content.",
            details={"destination": destination, "user": target_user},
        )

    if f"User_Alias AOSD_USER = {target_user}" not in content:
        return PrivilegedCheckResult(
            ok=False,
            message=f"Sudoers file exists but is not configured for user '{target_user}'.",
            details={"destination": destination, "user": target_user},
        )

    ok_valid, validation_msg = _run_visudo_check(destination)
    if not ok_valid:
        return PrivilegedCheckResult(
            ok=False,
            message="Sudoers file exists but failed visudo validation.",
            details={"destination": destination, "validation": validation_msg, "user": target_user},
        )

    return PrivilegedCheckResult(
        ok=True,
        message="Privileged sudo setup is active for this user.",
        details={"destination": destination, "validation": validation_msg, "user": target_user},
    )


def setup_privileged_access(
    *,
    user: Optional[str] = None,
    dry_run: bool = False,
    destination: str = "/etc/sudoers.d/assistant-os",
) -> PrivilegedSetupResult:
    if os.name != "posix":
        return PrivilegedSetupResult(
            ok=False,
            message="This setup is only supported on Linux/Unix.",
            details={},
        )

    ok_user, user_or_error = _resolve_target_user(user)
    if not ok_user:
        return PrivilegedSetupResult(ok=False, message=user_or_error, details={})
    target_user = user_or_error

    installed = _detect_installed_commands()
    if not installed:
        return PrivilegedSetupResult(
            ok=False,
            message="No supported package/system commands were detected.",
            details={"supported": SUPPORTED_COMMANDS},
        )

    cmd_specs = _build_command_specs(installed)
    content = _build_sudoers_content(target_user, cmd_specs)

    with tempfile.NamedTemporaryFile("w", delete=False, prefix="assistant_sudoers_", suffix=".tmp") as tmp:
        tmp_path = tmp.name
        tmp.write(content)
    os.chmod(tmp_path, 0o440)

    try:
        ok_check, check_msg = _run_visudo_check(tmp_path)
        if not ok_check:
            return PrivilegedSetupResult(
                ok=False,
                message="Generated sudoers file did not pass visudo validation.",
                details={"validation": check_msg, "file": tmp_path},
            )

        if dry_run:
            return PrivilegedSetupResult(
                ok=True,
                message="Dry-run complete. Generated and validated sudoers content.",
                details={
                    "user": target_user,
                    "destination": destination,
                    "detected_commands": installed,
                    "content": content,
                },
            )

        if os.geteuid() == 0:
            os.makedirs(os.path.dirname(destination), exist_ok=True)
            shutil.copyfile(tmp_path, destination)
            os.chmod(destination, 0o440)
            owner = pwd.getpwnam("root").pw_uid
            group = grp.getgrnam("root").gr_gid
            os.chown(destination, owner, group)
        else:
            install_cmd = ["sudo", "install", "-m", "440", "-o", "root", "-g", "root", tmp_path, destination]
            proc = subprocess.run(
                install_cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            if proc.returncode != 0:
                details = (proc.stdout or "") + ("\n" + proc.stderr if proc.stderr else "")
                return PrivilegedSetupResult(
                    ok=False,
                    message="Failed to install sudoers file. Run this command with sudo/root.",
                    details={"error": details.strip(), "command": " ".join(install_cmd)},
                )

        if os.geteuid() == 0:
            ok_final, final_msg = _run_visudo_check(destination)
        else:
            ok_final, final_msg = _run_visudo_check(destination, use_sudo=True)
        if not ok_final:
            return PrivilegedSetupResult(
                ok=False,
                message="Installed sudoers file failed final validation.",
                details={"validation": final_msg, "destination": destination},
            )

        return PrivilegedSetupResult(
            ok=True,
            message="Privileged setup completed successfully.",
            details={
                "user": target_user,
                "destination": destination,
                "detected_commands": installed,
                "validation": final_msg,
            },
        )
    finally:
        try:
            os.unlink(tmp_path)
        except Exception:
            pass
